# Generated by Django 3.2.4 on 2021-09-03 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_alter_materialespractica_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Clave')),
                ('foto', models.ImageField(null=True, upload_to='fotos', verbose_name='Fotografía')),
                ('nombreEmpleado', models.TextField()),
                ('skills', models.CharField(max_length=15)),
                ('telefono', models.CharField(max_length=11)),
                ('domicilio', models.TextField()),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
    ]
