# Generated by Django 3.2.4 on 2021-09-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_auto_20210903_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialespractica',
            name='material',
            field=models.JSONField(default={}),
        ),
    ]
